IF(
	EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Report')
	AND
	EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Office')
	AND
	NOT EXISTS(SELECT 1 FROM SYS.COLUMNS WHERE Name='OfficeId' AND Object_id=Object_id('dbo.Report'))
)
BEGIN
	ALTER TABLE [dbo].[Report]
	ADD [OfficeId] [bigint] NOT NULL

	ALTER TABLE [dbo].[Report]
	ADD CONSTRAINT [FK_Report_Office] FOREIGN KEY
	(
		[OfficeId]
	)
	REFERENCES [Office]([Id])
END