IF (EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Category' AND COLUMN_NAME='DateCreated'))
BEGIN
	ALTER TABLE [dbo].[Category] ALTER COLUMN DateCreated DATETIME NOT NULL
END