IF (NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Order')
	AND 
	EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='User')
	AND 
	EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Category'))
BEGIN
	CREATE TABLE [dbo].[Order](
		[Id] [bigint] IDENTITY(1, 1) NOT NULL,
		[UserId] [bigint] NOT NULL,
		[ItemId] [bigint] NULL,
		[Amount] [int] NULL,
		[Description] [varchar] (500) NULL,
		[State] [tinyint] DEFAULT 0,
		[DateCreated] [datetime] NULL,
		[DateModified] [datetime] NULL,
		[IsDeleted] [bit] DEFAULT 0,
	CONSTRAINT [FK_Order_User] FOREIGN KEY 
	(
		[UserId]
	)
	REFERENCES [User]([Id]),
	CONSTRAINT [FK_Order_Item] FOREIGN KEY 
	(
		[ItemId]
	)
	REFERENCES [Item]([Id]),
	CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)	ON [PRIMARY]
END