IF(NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Order' AND COLUMN_NAME='OfficeId'))
BEGIN
	ALTER TABLE [dbo].[Order]
	ADD OfficeId bigint NOT NULL 
	CONSTRAINT DF_Order_OfficeId DEFAULT 1
	CONSTRAINT FK_Order_OfficeId FOREIGN KEY REFERENCES Office(Id)
END