IF ( EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='User' ))
BEGIN
	IF ( NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='User' AND COLUMN_NAME='DateModified'))
	BEGIN
		ALTER TABLE [dbo].[User] ADD DateModified DATETIME NULL
	END

	IF ( NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='User' AND COLUMN_NAME='ResetToken'))
	BEGIN
		ALTER TABLE [dbo].[User] ADD ResetToken VARCHAR(40) NULL
	END

	IF ( NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='User' AND COLUMN_NAME='ResetTokenExpirationTime'))
	BEGIN
		ALTER TABLE [dbo].[User] ADD ResetTokenExpirationTime DATETIME NULL
	END

	IF ( NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='User' AND COLUMN_NAME='IsActive'))
	BEGIN
		ALTER TABLE [dbo].[User] ADD IsActive BIT NOT NULL CONSTRAINT DF_User_IsActive DEFAULT(1)
	END
END