IF (NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Comment')
	AND 
	EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='User')
	AND 
	EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Order'))
BEGIN
	CREATE TABLE [dbo].[Comment](
		[Id] [bigint] IDENTITY(1, 1) NOT NULL,
		[UserId] [bigint] NOT NULL,
		[OrderId] [bigint] NOT NULL,
		[Text] [varchar] (500) NOT NULL,
		[DateCreated] [datetime] NOT NULL,
		[DateModified] [datetime] NULL,
		[IsDeleted] [bit] DEFAULT 0,
	CONSTRAINT [FK_Comment_User] FOREIGN KEY 
	(
		[UserId]
	)
	REFERENCES [User]([Id]),
	CONSTRAINT [FK_Comment_Order] FOREIGN KEY 
	(
		[OrderId]
	)
	REFERENCES [Order]([Id]),
	CONSTRAINT [PK_Comment] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)	ON [PRIMARY]
END