// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inovatec.OfficeManagementTool.Models.Entity
{
    public partial class Equipment
    {
        public Equipment()
        {
            Reports = new HashSet<Report>();
        }

        public long Id { get; set; }
        public long ItemId { get; set; }
        public long? UserId { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime? DateModified { get; set; }

        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}