// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inovatec.OfficeManagementTool.Models.Entity
{
    public partial class Notification
    {
        public long Id { get; set; }
        public string Data { get; set; }
        public string Description { get; set; }
        public bool? IsRead { get; set; }
        public long UserId { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual User User { get; set; }
    }
}