// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inovatec.OfficeManagementTool.Models.Entity
{
    public partial class Report
    {
        public Report()
        {
            Comments = new HashSet<Comment>();
        }

        public long Id { get; set; }
        public long UserId { get; set; }
        public long? EquipmentId { get; set; }
        public string Description { get; set; }
        public byte? State { get; set; }
        public byte? Category { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public bool? IsDeleted { get; set; }
        public long OfficeId { get; set; }

        public virtual Equipment Equipment { get; set; }
        public virtual Office Office { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}